### ISSUE TITLE
계획 세우고 실천할 때 필요한 점

### ISSUE THREAD

**Issue by jongfeel** [kapitalismho/temporaryname#2]
노션에 공유해 주신 계획은 현재 저랑 같이 리뷰할 프로젝트 외에
모든 개인 공부 및 활동에 대한 스케줄이 포함되어 있습니다.

저랑 같이 리뷰할 프로젝트의 계획은 별도로 세워 보셨으면 좋겠습니다.

**Comment by kapitalismho** [comment]
말씀하신대로 개인 일정과 프로젝트 계획을 분리하였습니다.
리드미와 디스커션에 있는 주소 또한 변경하였습니다.

**Comment by jongfeel** [comment]
그런데 비공개네요, 공개로 바꿔주세요.

**Comment by kapitalismho** [comment]
부주의했네요... 공개로 바꿨습니다!!
